### ISSUE TITLE
Carthage badge is missing

### ISSUE THREAD

**Issue by TofPlay** [gizmosachin/Monocle#1]
On your `README.md` [![Carthage compatible](https://img.shields.io/badge/Carthage-Compatible-brightgreen.svg?style=flat)](https://github.com/Carthage/Carthage) is missing.

**Comment by gizmosachin** [comment]
Fixed in https://github.com/gizmosachin/Monocle/commit/765a81ac8cb82eaa8a36c4580931f84dc0bbd374.
